// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICb4nwhWimTe7lcb6oQyVRw35sWhbiOI',
    appId: '1:78707370379:web:d59b0d429e4f8c9e76678e',
    messagingSenderId: '78707370379',
    projectId: 'satva-dhara-erp',
    authDomain: 'satva-dhara-erp.firebaseapp.com',
    storageBucket: 'satva-dhara-erp.firebasestorage.app',
    measurementId: 'G-ZDFZHVNNKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjiouCRCuB2Ucr00BsgFFJr2uPvPQF9c',
    appId: '1:78707370379:android:46bf090e45230f3e76678e',
    messagingSenderId: '78707370379',
    projectId: 'satva-dhara-erp',
    storageBucket: 'satva-dhara-erp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Jj8tRsO1uwsbqg6BvPcRg1FXgwOgh2A',
    appId: '1:78707370379:ios:c8cb15a8a17f0c8776678e',
    messagingSenderId: '78707370379',
    projectId: 'satva-dhara-erp',
    storageBucket: 'satva-dhara-erp.firebasestorage.app',
    iosBundleId: 'com.example.satvaDharaErp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Jj8tRsO1uwsbqg6BvPcRg1FXgwOgh2A',
    appId: '1:78707370379:ios:c8cb15a8a17f0c8776678e',
    messagingSenderId: '78707370379',
    projectId: 'satva-dhara-erp',
    storageBucket: 'satva-dhara-erp.firebasestorage.app',
    iosBundleId: 'com.example.satvaDharaErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICb4nwhWimTe7lcb6oQyVRw35sWhbiOI',
    appId: '1:78707370379:web:0c7a66467f1ecf2f76678e',
    messagingSenderId: '78707370379',
    projectId: 'satva-dhara-erp',
    authDomain: 'satva-dhara-erp.firebaseapp.com',
    storageBucket: 'satva-dhara-erp.firebasestorage.app',
    measurementId: 'G-DHZWE8QZLK',
  );
}
